--[[
	GameConfig
	Top-level switches for the whole kingdom. Every other config module holds
	the numbers for one system; this one decides how the systems behave
	together.
]]

local GameConfig = {}

-- "Server": each server is its own kingdom. Ranks exist only while the
--           player is in that server; XP and lifetime stats persist globally.
-- "Global": all servers share one hierarchy (MemoryStore + DataStore backup).
--           Ranks persist while offline until GlobalRankInactivityRelease.
GameConfig.KingdomScope = "Server"

-- How empty/vacant rank slots are filled (see HierarchyModel):
--   CASCADE      one rung at a time, highest XP first (MinXP + cooldown apply)
--   HIGHEST_XP   highest XP from ANY lower rank may jump into the vacancy
--   FIRST_PLAYER one rung at a time, longest-present player first
--   MANUAL       no automatic promotion (admins / government appoint)
--   HYBRID       CASCADE + per-rank MinActivePlayers population gates (default)
GameConfig.EmptyRankFillingMode = "HYBRID"

-- Applied to every promotion (seconds between two promotions of one player).
-- Ranks may override with RankConfig PromotionCooldown.
GameConfig.PromotionCooldownSeconds = 90

-- Seconds a demoted/removed player is blocked from being re-promoted, so a
-- high-XP player who was removed is not instantly pulled back up.
GameConfig.DemotionPromotionBlockSeconds = 45 * 60

-- When a player joins a server-scoped kingdom:
--   "Bottom"          always enter at the bottom rank (default, recommended)
--   "RestoreIfVacant" return to the saved rank only if a slot is empty and the
--                     gates allow it (never above the saved rank)
GameConfig.RejoinPolicy = "Bottom"

-- Global kingdom tuning.
GameConfig.Global = {
	HierarchyMapName = "KingdomHierarchy_v1",
	HierarchyKey = "State",
	BackupDataStore = "KingdomHierarchyBackup_v1",
	BackupIntervalSeconds = 300,
	SyncIntervalSeconds = 30, -- batch XP + presence sync
	OnlineWindowSeconds = 150, -- seen within this window = online
	RankInactivityReleaseSeconds = 3 * 24 * 3600, -- offline this long = slot released
	ForgetBottomRankAfterSeconds = 3600, -- drop idle bottom-rank entries from the doc
	PromoteOfflinePlayers = false,
	MessagingTopic = "KingdomHierarchy",
	PersistTreasury = true, -- treasury + tax policy shared by all servers
	TreasuryDataStore = "KingdomTreasury_v1",
}

-- Total XP formula (current life). Weights are multiplied by each category.
GameConfig.XPWeights = {
	Job = 1,
	Management = 1,
	Leadership = 1,
	Contribution = 1,
}

-- XP anti-abuse limits (applied after all multipliers).
GameConfig.XPLimits = {
	MaxSingleAward = 2500,
	MaxPerMinute = 4000, -- rolling 60s window, excess is dropped and flagged
	MaxTotalMultiplier = 2.0, -- all multipliers combined are clamped to this
	MinTotalMultiplier = 0.1,
}

-- Players are AFK after this many seconds with no movement or interaction.
GameConfig.AFKSeconds = 120

-- Data
GameConfig.Data = {
	PlayerStore = "KingdomPlayers_v1",
	BanStore = "KingdomBans_v1",
	AuditStore = "KingdomAudit_v1",
	LeaderboardStore = "KingdomLifetimeXP_v1",
	AutosaveSeconds = 120,
	SessionLockTimeoutSeconds = 600, -- a lock older than this is considered dead
	LoadRetries = 6,
	SaveRetries = 5,
	-- In Studio without API access the game runs on in-memory data.
	UseMockInStudioWithoutAPI = true,
}

-- Chat role prefixes ([KING], [DUKE] ...). Generated by the server only.
GameConfig.Chat = {
	ShowRankTags = true,
	ShowTitles = true,
}

-- Developer test tools (bots, simulations). Enabled automatically in Studio.
GameConfig.TestingMode = {
	EnabledInStudio = true,
	EnabledInLiveServers = false,
	MaxBots = 150,
}

-- Debug logging. Turn Enabled off for production; per-tag overrides allowed.
GameConfig.Debug = {
	Enabled = true,
	Tags = {
		-- RankService = true,
		-- PromotionService = true,
		-- EconomyService = false,
	},
}

-- Kingdom-wide announcement thresholds (by rank Order). Lower ranks only
-- notify the players involved, so busy servers are not spammed.
GameConfig.Announcements = {
	VacancyMinOrder = 4, -- "SERGEANT POSITION OPEN"
	PromotionMinOrder = 3, -- "PlayerA has been promoted to Guard."
	DeathMinOrder = 4, -- "Lord X has fallen."
}

-- Respawn
GameConfig.RespawnSeconds = 6
GameConfig.MaxRespawnWaitForDeathSave = 15

return GameConfig
